language: node_js
node_js:
- 16

install:
- echo "Installing serverless, library"
- npm install serverless --save-dev --force
- npm install --save-dev --force

before_install:
- echo "Jump into backend directory"
- cd backend

script:
- echo "Running scripts"
- sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_KEY --profile $AWS_PROFILE
- npm install serverless-webpack --save-dev --force
- npm install serverless-iam-roles-per-function --save-dev --force
- npm install serverless-plugin-tracing --save-dev --force
- npm install serverless-aws-documentation --save-dev --force
- export NODE_OPTIONS=--max_old_space_size=4096
- serverless deploy --profile $AWS_PROFILE

after_success:
- echo "Finish setting dev environment"
